config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "home#index"

  devise_for :users, :controllers => {:registrations => "users/registrations"}

  resources :home, only: :index
  resource :dashboard, only: :show

  resources :documentation, only: [:index, :show] do
    resource :badge, only: :show, controller: 'documentation/badges'
    resource :approve, only: :create, controller: 'documentation/approve'
  end

  resources :invites, only: :create

  namespace :settings do
    resource :document_stores, only: [:show, :update] do
      resources :github_wiki, only: [:new, :create], controller: 'document_stores/github_wiki'
      resources :intercom_helpdesk, only: [:new, :create], controller: 'document_stores/intercom_helpdesk'
    end
    resources :users
  end

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/controllers/documentation/approve_controller.rb
class Documentation::ApproveController < ApplicationController
  def create
    document = Document.find(params[:documentation_id])
    document.reviews << Review.create(review_by: current_user, approved: true)
    document.update!(last_review: Time.now, assigned_to: nil)

    redirect_to documentation_index_path
  end
end

app/controllers/documentation/badges_controller.rb
class Documentation::BadgesController < ApplicationController
  def show
    @document = Document.find(params[:documentation_id])
    generate_image

    send_file('/tmp/badge.jpg',
              filename: 'badge',
              type: 'image/png',
              disposition: 'inline')
  end

  private

  def generate_image
    base_image = MiniMagick::Image.open("#{Rails.root}/app/assets/images/badge_base.png")
    base_image.combine_options do |c|
      if @document.last_review
        c.draw "text 162,30 \"#{@document.last_review.strftime('%d %B %Y')}\""
        c.draw "text 172,51 \"#{@document.reviews.last.review_by.email}\""
      else
        c.draw 'text 162,30 "Not Yet Reviewed"'
      end
      # c.font '-*-helvetica-*-r-*-*-18-*-*-*-*-*-*-2'
      # c.fill("#FFFFFF")
    end

    base_image.write('/tmp/badge.jpg')
  end
end

app/controllers/documentation_controller.rb
class DocumentationController < ApplicationController
  before_action :authenticate_user!

  def index
    @documents = Document.all
  end

  def show
    @document = Document.find(params[:id])
  end
end

app/views/documentation/index.haml
%table{ cellspacing: 0 }
  %thead
    %tr
      %td Title
      %td Last Reviewed
      %td
      %td Assigned
      %td
  %tbody
    - @documents.each do |document|
      %tr
        %td
          - if document.source == 'github'
            %i.fa.fa-2x.fa-github
          - elsif document.source == 'intercom'
            = image_tag 'intercom.png', style: 'height: 22px;'
          - else
            %i.source-icon= document.source[0].capitalize
          &nbsp;
          = link_to document.title, documentation_path(document.id)
        %td= document.last_review.present? ? document.last_review : '-'
        %td
          = link_to 'view', document.original_documentation
        %td
          %i.fa.fa-user-circle.fa-2x{ style: 'color:#CCC' }
          - if document.assigned_to.present?
            - if document.assigned_to.name.present?
              = document.assigned_to.name
            - else
              = get_name_from(document.assigned_to.email)
          - else
            N/A
        %td
          = link_to '👍', documentation_approve_path(document.id), method: :create, data: { confirm: 'I agree that this all looks A.OK?'}, style: 'text-decoration: none;'
     

app/views/documentation/show.haml
%center
  .col-6
    %h2 Add this to your page
  .col-6
    = image_tag documentation_badge_path(documentation_id: params[:id])
    %br
    %textarea{ rows: 1, cols:48 }
      = raw(image_tag documentation_badge_url(documentation_id: params[:id]))

%table{ cellspacing: 0 }
  %thead
    %tr
      %td Reviewed At
      %td Reviewed By
  %tbody
    - @document.reviews.order(created_at: :desc).each do |review|
      %tr
        %td= review.created_at.strftime('%d %B %Y %H:%M') 
        %td
          %i.fa.fa-user-circle.fa-2x{ style: 'color:#CCC' }
          - if review.review_by.present?
            - if review.review_by.name.present?
              = review.review_by.name
            - else
              = get_name_from(review.review_by.email)
          - else
            N/A